services:
  - type: web
    name: crenal-dashboard
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9   # <= aquí el fix (usa 3 números)
      - key: STREAMLIT_SERVER_HEADLESS
        value: "true"
